#-------------------------------------------------------------------------------
# Name:        PythonPunk0.1
# Purpose:     For all to enjoy
#
# Author:      Nathan
#
# Created:     14/03/2013
# Copyright:   (c) Nathan 2013
# Licence:     Attribution-NonCommercial-NoDerivs 3.0 Unported
#-------------------------------------------------------------------------------
import sys
import time
from sys import argv
print("Welcome to the hi-tech world of PythonPunk!")
time.sleep(3)
print("In this world there is a war")
time.sleep(3)
print("It is between the United Planets rulled by the emporor and a rouge general and his army")
time.sleep(4)
print("--------------")
print(" CHAPTER 0 ")
print("--------------")
print("You have been recruited into the world through a time-travel portal")
time.sleep(3)
print("You find yourself in what look likse a small starship wth two men in armor")
time.sleep(3)
plrname = input("Tell us your name. Asks the man that brought you throught the portal")
time.sleep(3)
print("Nice to meet you " + str(plrname) + ". Said the other man.")
time.sleep(3)
print("Right as he said that he stood up as the computer said 'WARNING incoming blaster fire detected WARNING!'")
time.sleep(5)
# At this time you would be able to chose a class but only one till we get to version 2, so no need to ask
print("'Here take this'.  Said the man as he threw you a assualt rifle.")
time.sleep(3)
print("Were going down! said the man that got up earlier")
time.sleep(3)
print("3 hours later after you crashed")
time.sleep(3)
print("Hey this ones awake!")
time.sleep(3)
print("Where am I? you asked")
time.sleep(3)
print("Your ship went down and your two guards didnt make it, may I ask for your name?")
time.sleep(3)
print("The names " + str(plrname) + ". You said to the Medical Officer")
time.sleep(3)
print("The room was sudenly silent and a man who had a Commanders pin walked in")
time.sleep(3)
print("Whats going on? you asked")
time.sleep(3)
print("Welcome to templar squad, soldier. said the commander")
time.sleep(3)
print("Its about time somone filled you in, you are a soldier who is going to lead the rebelion after this war is over but we needed you now.")
time.sleep(4)
print("--------------")
print(" CHAPTER 1 ")
print(" Templar Squad ")
print("--------------")
#At this time Matthew Royster was added to team as Assistan to Lead Dev Nathan
#Please send support info to techpunkcreative@gmail.com
time.sleep(3)
print("Commander, Sir, the Juggernuat Forces are marching in from the west!")
time.sleep(3)
print("Lets move Templar Squad! said the Commander")
time.sleep(3)
print("That Means you " + str(plrname) + "!")
time.sleep(3)
print("You are given a suit of armor and a better gun and move towwards the Battle Feild")
time.sleep(3)
print("INCOMING! yelled a squad mate as lasers and rockets flew overhead")
time.sleep(3)
print("Get down! yelled the commander")
time.sleep(3)
print(str(plrname) + " Move around and flank")
time.sleep(3)
print("You moved around to there encampment and see 3 men on large Machines firing off rockets")
time.sleep(3)
print("Rember to use the numbers inside the () for choices")
time.sleep(3)
choice1 = int(input("Do you snipe the drivers(1) or stealth and bomb the machines(2)"))
time.sleep(3)
if(choice1 == 1):
           print("You manage to snipe them and notice that you are a nuatural")
           time.sleep(3)
           print(str(plrname) + " They stopped firing, was that you? asks the Com.")
           time.sleep(3)
           print("Yes, sir!")
           time.sleep(3)
           print("Exellent work, soldier")
if(choice1 == 2):
           print("You, using your suits built in cloak, are ready to bomb the machines")
           time.sleep(3)
           print("You contact the commander")
           time.sleep(2)
           print("Sir, I have palce bombs on there Missile Launchers.")
           time.sleep(3)
           print("Exellent work, wait for my signal")
           time.sleep(3)
           print("NOW! yelled the commander")
           time.sleep(1)
           print("KA-BOOM!")
           time.sleep(3)
           print("Great work, soldier")
#End of work on 3/15/2013

