#-------------------------------------------------------------------------------
# Name:        PythonPunk1.0
# Purpose:     For all to enjoy
#
# Author:      Nathan and Matthew
#
# Created:     14/03/2013
# Copyright:   (c) Nathan 2013
# Licence:     Attribution-NonCommercial-NoDerivs 3.0 Unported
#-------------------------------------------------------------------------------
import sys
import time
from sys import argv
print("In a world before our own")
time.sleep(3)
print("There was a devastating war")
time.sleep(3)
print("A rebellion continued to fight for the fallen army")
time.sleep(3)
print("But in order to prevent the army from falling")
time.sleep(3)
print("They needed him...a hero...the leader of the rebels")
time.sleep(3)
print("........................................................")
time.sleep(3)
print("Whe......Where am I?")
time.sleep(3)
print("Don't worry you were just safely transported through a portal from the future.")
time.sleep(3)
print("Who are you?")
time.sleep(3)
print("Why am I even here?")
time.sleep(3)
print("First, I am the commander of the United Military Specialist Force or UMSF for short.")
time.sleep(3)
print("You are here for the specific reason of help this army survive and win this war.")
time.sleep(3)
print("You will be the hero we need with your strategies.")
time.sleep(3)
print("We can win this war with your help.")
time.sleep(3)
print("No I need to go back I have a family.")
time.sleep(3)
print("Why did it have to be me?")
time.sleep(3)
print("Do you not listen?")
time.sleep(3)
print("I already said that it is YOU, YOU are the one.")
time.sleep(3)
print("In the future you will lead a rebellion after this army falls.")
time.sleep(3)
print("With your help we can win this war without falling.")
time.sleep(3)
print("The current situation is the general from across the galaxy know as Dead Mind as we call him.")
time.sleep(3)
print("As implied he is fairly...well...not intelligent to put it nicely.")
time.sleep(3)
print("He was ordering all of us to give him our resources and we refused.")
time.sleep(3)
print("He is forming a new empire and he is making us his first target.")
time.sleep(3)
print("Why would he even do such a thing?")
time.sleep(3)
print("Obviously he isn't that smart for doing something like that.")
time.sleep(3)
print("We are going to get you briefed for your first mission soon.")
time.sleep(3)
print("COMMANDER!!!")
time.sleep(3)
print("This is Lt.Thomas we have a missile coming from sector 5.")
time.sleep(3)
print("E.T.A. of 2 minutes, take cover, out.")
time.sleep(3)
print("Come along.")
time.sleep(2)
print("We need you to meet the rest of your squadron.")
time.sleep(3)
print("Hurry before the missiles get here.")
time.sleep(6)
print("Welcome to your barracks, I will be back later, met all of your squadmates.")
time.sleep(3)
print("Hey a new guy, I am Engineer Mathias.")
time.sleep(3)
print("I am the strongest one here and i am also the most trusted.")
time.sleep(3)
print("When is dinner my muscles don't feed themselves.")
time.sleep(3)
print("I am Chief Selah, I am goin to be watching every move everyone makes.")
time.sleep(3)
print("I am fairly smart, I like to have control so dont make me conform, I won't change.")
time.sleep(3)
print("I am Sargent Isiah, I will be your second in caommand.")
time.sleep(3)
print("I am the most serious and i am usually pretty quiet except around my friends.")
time.sleep(3)
print("You have already met me, I am Lt.Thomas.")
time.sleep(3)
print("I am the smartest one, I also am the pilot and your tech guy.")
time.sleep(3)
print("The commander is awaiting for us.")
time.sleep(3)
print("You will get your armor, equipment, and weaponry from the aromry after briefing.")
time.sleep(3)
print("We need to move out the commander is waiting.")
#REVAMP 3/15/2013
print("PYTHON PUNK StarBucks Edition")
plrname = input("What is your name?")
time.sleep(4)
PAK = input("PYTHON PUNK *Press Return to continue* PYTHON PUNK")
time.sleep(3)
print("")
print("---------")
print("-Chapter-")
print(" A Hero ")
print("---------")
time.sleep(4)
print("Hey Capitan, sir were moving out said the lut.")
time.sleep(4)
print("Right lets move! you said")
time.sleep(4)
print("'We have located a enemy scout camp' said the Commander")
time.sleep(4)
print("We need to take it out and it is a stealth mission so thats where you come in")
time.sleep(4)
#FACE-BOARD
print("We have 3 options to get in there said your Sargent")
time.sleep(4)
print("Stealth drop,ATV,or on foot aproach, I would recomend Stealth Drop")
time.sleep(4)
choice1 = int(input("Will you Stealth Air Drop(1),ATV(2),or go on foot(3)"))
time.sleep(4)
print("You heard the Man were moving out!")
time.sleep(4)
if(choice1 == 1):
    print("This is lut. Thomas to hangar bay 7, we need accses to the Stealth Talon")
    time.sleep(4)
    print("This is Private Stephen, Im going to need your pilot ID, sir")
    time.sleep(4)
    print("72899, over")
    time.sleep(4)
    print("Hangar Bay 7 is all yours sir")
    time.sleep(4)
    print("Give me like 10 minutes and your ship will be ready sir")
    time.sleep(4)
    print("Lets move to the armory")
    time.sleep(4)
    print("Welcome to the UMSFA I will need a DNA scan of Capitan " + str(plrname) + ".")
    time.sleep(4)
    print("DNA Scan in progress, complete Capitan" + str(plrname) + " reconized, force field offline, you may continue.")
    time.sleep(4)
    print("You need to be introduced to the United Military Special Forces Armory, Cap")
    time.sleep(4)
    print("On this rack the armorer said while pointing to a large rack with nothing on it")
    time.sleep(4)
    print("We have weapons he said as he pressed a button reveling several weapons")
    time.sleep(4)
    print("And over here we have armor as he pointed to several suits of white and Black armor with lots of stealth tech and ammo")
    time.sleep(4)
    print("Hey Templar Squad thats NOT new around here go suit up")
    time.sleep(4)
    print("And now your gun this is the MadBull 808 it shoots high-explosive nano shells and is a Burst Fire its the weapon you are used to")
    time.sleep(4)
    print("Right and my armor is the BreakPoint 200 I would asume")
    time.sleep(4)
    print("You asume right now suit up!")
else:
    print("As you move out you and your squad run into there forrward scout party!")
    time.sleep(4)
    print("You fight to the last and almost make it out of there alive!, almost, the worlds will rmeber your bravery")
    time.sleep(4)
    print("GAME OVER")
    sys.exit
print("Sir, this is Tom, I have the ship ready!")
time.sleep(4)
print("On are way you reply")
time.sleep(4)
print("As you board the ship you notice a slight head-ache")
time.sleep(4)
print("You OK sir?")
time.sleep(4)
print("Yeah,Yeah I will be fine")
time.sleep(4)
print("Were at the drop sight")
time.sleep(4)
print("Everyone out!")
time.sleep(4)
print("You aproach the ridge above the camp")
time.sleep(4)
print("They have explosives if anyone were to assualt sir we need to assisnate the trigger holder")
time.sleep(4)
print("Yeah I have some ideas")
time.sleep(4)
choice2 = int(input("Using a disquise you sneak into the armored tent, will you kill the guards and triggger with Guns(1) or Knifes(2)"))
time.sleep(4)
if(choice2 == 1):
    print("HEY put those down! yell the guards")
    print("pop pop pop goes the silenced dual warriors")
    time.sleep(4)
    print("I have secured the intel! you report")
else:
    print('Hey no weapons allowed')
    time.sleep(4)
    print("Our leader must see the runes on this blade")
    time.sleep(4)
    print("You get up close and have the leader 'look at the blades' as you KILL EM!")
    time.sleep(4)
    print("Then the guards shoot you down!")
    time.sleep(4)
    print("GAME OVER")
    time.sleep(4)
    sys.exit
print("I need options, I just angried a large amount of armed men")
time.sleep(4)
print("We can provied backup if you need or Tom sais he can Teleport you out,sir")
time.sleep(4)
print("Or you could test out the new dual machetes sais Tom")
time.sleep(4)
choice3 = int(input("Will you Beam Out(1),Get Backup(2),or GO COMMANDO(3)"))
if(choice3 == 1):
    print("Sir they jammed the signal your on your own!!!")
    time.sleep(4)
    print("Right as you get that message a stealth scout sneaked pass you and pulled the trigger!")
    time.sleep(4)
    print("GAME OVER")
    sys.exit
if(choice3 == 2):
    print("Were on are way down")
    time.sleep(4)
    print("Sir there comming left siad sarge as she came down the ridge")
    time.sleep(4)
    print("Move to the right and bomb there entry!")
    time.sleep(4)
    print("Yes sir!")
    time.sleep(4)
    print("I got the incomming from mid said Matthias as he made it down the ridge")
    time.sleep(4)
    print("Well that was close but I think we made it you said as the heat died down")
if(choice3 == 3):
    print("Here cetch said Tom as he tpd in two swords with electric stuns")
    time.sleep(4)
    print("ARRRRRR")
    print("SLASH,CLANG, and Be-headed fool you said")
    time.sleep(4)
    print("No wonder we needed you said your Chief")
print("Sir, we have a problem!")
time.sleep(4)
print("Well dont be suspensful")
time.sleep(4)
print("That was a order Lt!")
time.sleep(4)
print("S..s...s..ir INCOMING AIR STRIKE!!!")
time.sleep(4)
print("Get me the commander you say as you climb abord the Talon")
time.sleep(4)
print("Yes, Capitan")
time.sleep(4)
print("We have a incomming air strike")
time.sleep(4)
print('---------')
print('-CHAPTER-')
print("Spade Force")
print('---------')